# Generated by Django 4.2.26 on 2025-11-12 02:24

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LoadType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlateNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TruckType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TruckingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('debit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('final_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('remarks', models.TextField()),
                ('reference_number', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('account_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.accounttype')),
                ('back_load', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='back_trucking_accounts', to='app.loadtype')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.driver')),
                ('front_load', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='front_trucking_accounts', to='app.loadtype')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.route')),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.truck')),
            ],
        ),
        migrations.AddField(
            model_name='truck',
            name='truck_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.trucktype'),
        ),
        migrations.CreateModel(
            name='TaxAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_number', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('remarks', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.accounttype')),
                ('plate_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.platenumber')),
                ('truck_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trucktype')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=255)),
                ('plate_number', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('debit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('final_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('remarks', models.TextField()),
                ('reference_number', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('driver', models.CharField(blank=True, max_length=255, null=True)),
                ('route', models.CharField(blank=True, max_length=255, null=True)),
                ('front_load', models.CharField(blank=True, max_length=255, null=True)),
                ('back_load', models.CharField(blank=True, max_length=255, null=True)),
                ('truck_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trucktype')),
            ],
        ),
        migrations.CreateModel(
            name='RepairAndMaintenanceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_number', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('remarks', models.CharField(max_length=255)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.accounttype')),
                ('plate_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.platenumber')),
                ('truck_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trucktype')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_number', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('remarks', models.CharField(max_length=255)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.accounttype')),
                ('plate_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.platenumber')),
                ('truck_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trucktype')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_number', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('driver', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('route', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('remarks', models.CharField(max_length=255)),
                ('front_load', models.CharField(max_length=255)),
                ('back_load', models.CharField(max_length=255)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.accounttype')),
                ('plate_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.platenumber')),
                ('truck_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trucktype')),
            ],
        ),
        migrations.CreateModel(
            name='FuelAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_number', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('driver', models.CharField(max_length=255)),
                ('liters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('route', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('remarks', models.CharField(max_length=255)),
                ('front_load', models.CharField(max_length=255)),
                ('back_load', models.CharField(max_length=255)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.accounttype')),
                ('plate_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.platenumber')),
                ('truck_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trucktype')),
            ],
        ),
        migrations.CreateModel(
            name='AllowanceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_number', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('remarks', models.CharField(max_length=255)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.accounttype')),
                ('plate_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.platenumber')),
                ('truck_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trucktype')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='app.role')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'One-Time Password',
                'verbose_name_plural': 'One-Time Passwords',
                'indexes': [models.Index(fields=['user', 'code', 'is_used'], name='app_otpcode_user_id_2d409d_idx'), models.Index(fields=['expires_at'], name='app_otpcode_expires_ace0fb_idx')],
            },
        ),
    ]
