# Generated by Django 5.2.7 on 2025-11-10 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'One-Time Password',
                'verbose_name_plural': 'One-Time Passwords',
                'indexes': [models.Index(fields=['user', 'code', 'is_used'], name='app_otpcode_user_id_2d409d_idx'), models.Index(fields=['expires_at'], name='app_otpcode_expires_ace0fb_idx')],
            },
        ),
    ]
