# Generated by Django 5.2.7 on 2025-11-02 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_truckingaccount_driver_route_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truckingaccount',
            name='plate_number',
        ),
        migrations.RemoveField(
            model_name='truckingaccount',
            name='truck_type',
        ),
    ]
