# Generated by Django 5.2.7 on 2025-11-02 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_truckingaccount_plate_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('truck_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trucktype')),
            ],
        ),
        migrations.AddField(
            model_name='truckingaccount',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.truck'),
        ),
    ]
