# Generated by Django 4.2.7 on 2025-11-02 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_truck_truckingaccount_truck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='truck_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.trucktype'),
        ),
    ]
