# Generated by Django 5.2.7 on 2025-11-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_truck_truck_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
