# Generated by Django 4.2.7 on 2025-11-03 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_truck_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='salaryaccount',
            name='account_type',
        ),
        migrations.AlterField(
            model_name='salaryaccount',
            name='truck_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trucktype'),
        ),
        migrations.AlterField(
            model_name='truckingaccount',
            name='account_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.accounttype'),
        ),
        migrations.AlterField(
            model_name='truckingaccount',
            name='back_load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_trucking_accounts', to='app.loadtype'),
        ),
        migrations.AlterField(
            model_name='truckingaccount',
            name='front_load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='front_trucking_accounts', to='app.loadtype'),
        ),
    ]
