# Generated by Django 4.2.7 on 2025-11-04 03:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_loadtype_remove_salaryaccount_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckingaccount',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
