# Generated by Django 5.2.7 on 2025-01-XX

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_truckingaccount_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckingaccount',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.driver'),
        ),
        migrations.AlterField(
            model_name='truckingaccount',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.route'),
        ),
        migrations.AlterField(
            model_name='truckingaccount',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.truck'),
        ),
        migrations.AlterField(
            model_name='truckingaccount',
            name='front_load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='front_trucking_accounts', to='app.loadtype'),
        ),
        migrations.AlterField(
            model_name='truckingaccount',
            name='back_load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='back_trucking_accounts', to='app.loadtype'),
        ),
    ]

