"""
Django settings for ong_backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.conf import settings as django_settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-flm4h*4s8z1+edev=%&c7)v$upwb056e%bjpcnl%o$+x^7ms^6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "rest_framework",
    'rest_framework.authtoken',
    "corsheaders",
    'djoser',
    "ong_backend",
    'app'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add WhiteNoise
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'app.middleware.CacheControlMiddleware',  # Add cache control headers
]

ROOT_URLCONF = 'ong_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.static',
            ],
        },
    },
]

WSGI_APPLICATION = 'ong_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'railway',
        'USER': 'postgres',
        'PASSWORD': 'zHZNzwesckltAdBBLTbGkwHPpWuGTmBI',
        'HOST': 'maglev.proxy.rlwy.net',
        'PORT': '19347',
        'OPTIONS': {
            'connect_timeout': 10,
        },
    }
}


# SQLite fallback (commented out)
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite8',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# WhiteNoise configuration
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    )
}

AUTH_USER_MODEL = 'app.User'

DJOSER = {
    'SERIALIZERS': {
        'user': 'app.serializers.CustomUserSerializer',
        'current_user': 'app.serializers.CustomUserSerializer',
        'user_create': 'app.serializers.CustomUserCreateSerializer',
    },
    'LOGIN_FIELD': 'username',
    'SEND_ACTIVATION_EMAIL': True,
    'ACTIVATION_URL': 'auth/activate/{uid}/{token}',
    'DOMAIN': os.environ.get('FRONTEND_DOMAIN', 'tnorf.gnikcurt.dpdns.org'),
    'SITE_NAME': os.environ.get('SITE_NAME', 'Ong Trucking'),
    'PROTOCOL': os.environ.get('FRONTEND_PROTOCOL', 'https'),
    'EMAIL': {
        'activation': 'app.emails.CustomActivationEmail',
    },
}

# DOMAIN = ('unieventify-7t3vl.ondigitalocean.app')
DOMAIN = ('tnorf.gnikcurt.dpdns.org')



# Email configuration
# EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'true').lower() == 'true'
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'false').lower() == 'true'
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', 15))
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'onboarding@ongtrucking.com')
SERVER_EMAIL = os.environ.get('SERVER_EMAIL', EMAIL_HOST_USER or DEFAULT_FROM_EMAIL)
SUPPORT_EMAIL = os.environ.get('SUPPORT_EMAIL', DEFAULT_FROM_EMAIL)

# CORS Settings
CORS_ALLOWED_ORIGINS = [
    "https://web-production-639bc.up.railway.app",
    "https://gno-frontend.onrender.com",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Allow all origins in development

# Explicitly allow common headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# For file uploads
CSRF_TRUSTED_ORIGINS = [
    "https://web-production-639bc.up.railway.app",
    "https://gno-frontend.onrender.com",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# Celery Configuration
# Railway provides both REDIS_URL (internal) and REDIS_PUBLIC_URL (external)
# Use internal URL for services in the same Railway project (faster, more secure)
REDIS_URL = os.environ.get('REDIS_URL', '')  # Internal URL (redis.railway.internal)
REDIS_PUBLIC_URL = os.environ.get('REDIS_PUBLIC_URL', '')  # Public URL (for external access)

# Prefer internal URL, fallback to public, then explicit, then localhost
if REDIS_URL:
    # Use Railway's internal REDIS_URL, different database numbers for different purposes
    CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', f'{REDIS_URL}/0')
    CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', f'{REDIS_URL}/0')
    REDIS_CACHE_URL = os.environ.get('REDIS_CACHE_URL', f'{REDIS_URL}/1')
elif REDIS_PUBLIC_URL:
    # Fallback to public URL if internal not available
    CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', f'{REDIS_PUBLIC_URL}/0')
    CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', f'{REDIS_PUBLIC_URL}/0')
    REDIS_CACHE_URL = os.environ.get('REDIS_CACHE_URL', f'{REDIS_PUBLIC_URL}/1')
else:
    # Fallback to explicit URLs or localhost
    CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
    CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
    REDIS_CACHE_URL = os.environ.get('REDIS_CACHE_URL', os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/1'))

# Cache configuration
# Use Redis cache for Celery progress tracking (shared between Django and Celery processes)
# This is required because LocMemCache is process-local and won't work with Celery workers
# Use Redis cache (Django 4.0+ has built-in Redis support)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': REDIS_CACHE_URL,
        'KEY_PREFIX': 'ong_backend',
        'TIMEOUT': 3600,  # 1 hour default
    }
}
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes
CELERY_RESULT_EXPIRES = 3600  # 1 hour

# Windows compatibility: Use solo pool instead of prefork (which doesn't work on Windows)
import sys
if sys.platform == 'win32':
    CELERY_WORKER_POOL = 'solo'
else:
    CELERY_WORKER_POOL = 'prefork'